// Code generated by riza; DO NOT EDIT.

package assembled

import (
	"context"
	"fmt"
)

type ListRequirementTypesResponse struct {
	RequirementTypes map[string]RequirementType `json:"requirement_types,omitempty"`
}

// Requirement types contain metadata about named set of staffing
// requirements.
type RequirementType struct {
	ID string `json:"id,omitempty"`

	// List of unique identifiers for activity types that count as scheduled
	// against the requirement.
	ActivityTypeIDs []string `json:"activity_type_ids,omitempty"`

	Name string `json:"name,omitempty"`
}

// Returns a list of all requirement type objects configured on the account.
func (c *Client) ListRequirementTypes(ctx context.Context) (*ListRequirementTypesResponse, error) {
	var resp ListRequirementTypesResponse
	if err := c.request(ctx, "GET", "/v0/requirement_types", nil, nil, &resp); err != nil {
		return nil, fmt.Errorf("ListRequirementTypes: %w", err)
	}
	return &resp, nil
}
